# Generated by Django 5.2.6 on 2025-09-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='create_account',
            new_name='account',
        ),
    ]
